# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=60)),
                ('login', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNumber', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
    ]
