# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 11:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2016, 10, 29, 13, 54, 59, 690133))),
                ('expired', models.DateTimeField(default=datetime.datetime(2016, 10, 30, 13, 54, 59, 690133))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
