# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='schoolName',
            new_name='username',
        ),
    ]
