# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0002_auto_20161023_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='expired',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounts',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(1, 3600)),
        ),
    ]
