# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0003_auto_20161023_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='duration',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 24, 17, 49, 45, 900370)),
        ),
    ]
