# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0003_auto_20161030_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 16, 1, 50, 648009)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 16, 1, 50, 648009)),
        ),
    ]
