# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0004_auto_20161023_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 24, 21, 25, 16, 441810)),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 25, 21, 25, 16, 441810)),
        ),
    ]
