# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 21:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0004_auto_20161106_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 6, 22, 30, 45, 940168)),
        ),
        migrations.AlterField(
            model_name='user',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 7, 22, 30, 45, 940168)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
