# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforma', '0005_auto_20161024_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 24, 21, 25, 25, 406816)),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='expired',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 25, 21, 25, 25, 406816)),
        ),
    ]
